### ISSUE TITLE
getting timeouts from infura

### ISSUE THREAD

**Issue by johannbarbie** [strudel-finance/monorepo#74]
```
{"errorType":"Error","errorMessage":"timeout","trace":["Error: timeout","    at Timeout._onTimeout (/var/task/node_modules/ethers/utils/web.js:54:20)","    at ontimeout (timers.js:436:11)","    at tryOnTimeout (timers.js:300:5)","    at listOnTimeout (timers.js:263:5)","    at Timer.processTimers (timers.js:223:10)"]}
```

don't know why

**Comment by johannbarbie** [comment]
maybe solved
